//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_DETAIL_INFO
    {
        public int ID { get; set; }
        public int CLASS_ID { get; set; }
        public int ENUM_ID { get; set; }
        public Nullable<int> TEXT_ID { get; set; }
        public string table_name { get; set; }
        public Nullable<int> note_id { get; set; }
        public int detail_type { get; set; }
        public Nullable<int> listindex { get; set; }
    }
}
