//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_LIB_RELATION_INFO
    {
        public int ID { get; set; }
        public string LIB_TABLE_NAME { get; set; }
        public string LIB_COLUMN_NAME { get; set; }
        public string SEC_TABLE_NAME { get; set; }
        public string SEC_COLUMN_NAME { get; set; }
        public string RELATION_TYPE_NAME { get; set; }
        public Nullable<short> RELATION_TYPE { get; set; }
        public Nullable<short> RELATION_GROUP { get; set; }
        public string LIB_SHOW_COLUMN_FORMAT { get; set; }
        public string LIB_FILTER_COLUMN_NAME { get; set; }
        public Nullable<short> IS_HIERARCHIC_RELATION { get; set; }
    }
}
