//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_METHOD_INFO
    {
        public int ID { get; set; }
        public int CLASS_ID { get; set; }
        public int TEXT_ID { get; set; }
        public string IMAGE { get; set; }
        public string NAME { get; set; }
        public Nullable<int> PARENT_ID { get; set; }
        public Nullable<int> TYPE { get; set; }
        public Nullable<int> ENTITY_TYPE { get; set; }
        public Nullable<int> note_id { get; set; }
        public Nullable<int> listindex { get; set; }
        public Nullable<int> ISMULTILINE { get; set; }
        public Nullable<int> GLOBALCONTROL { get; set; }
        public string SHORTCUT { get; set; }
    }
}
