//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_NOTIFICATION_INFO
    {
        public int ID { get; set; }
        public string TABLE_NAME { get; set; }
        public Nullable<int> ACTION_TYPE { get; set; }
        public string COLUMN_NAME { get; set; }
        public Nullable<int> APPLICATION_TYPE { get; set; }
        public Nullable<int> ACTION_TYPE_FOR_UP_LEVEL { get; set; }
        public Nullable<int> ACTION_TYPE_FOR_SAME_LEVEL { get; set; }
        public Nullable<int> ACTION_TYPE_FOR_DOWN_LEVEL { get; set; }
        public Nullable<int> ACTION_TYPE_FOR_CURRENT_ID { get; set; }
    }
}
