//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_OTHER_SYSTEMS
    {
        public int ID { get; set; }
        public Nullable<short> ENTITY_TYPE { get; set; }
        public string AUTH_URL { get; set; }
        public string AUTH_USER { get; set; }
        public string AUTH_PSW { get; set; }
        public string ACTION_URL { get; set; }
    }
}
