//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_OLD_NEW_DUTY_REPORT
    {
        public long NN { get; set; }
        public string CAPTION { get; set; }
        public Nullable<decimal> RES_TOTAL { get; set; }
        public Nullable<decimal> RES_COUNTER { get; set; }
        public Nullable<decimal> ORG_TOTAL { get; set; }
        public Nullable<decimal> ORG_COUNTER { get; set; }
        public Nullable<decimal> OTHER_TOTAL { get; set; }
        public Nullable<decimal> OTHER_COUNTER { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<decimal> TOTAL_COUNTER { get; set; }
    }
}
