//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_QUERY
    {
        public int ID { get; set; }
        public Nullable<int> QUERY_ID { get; set; }
        public string QUERY_STRING { get; set; }
        public Nullable<short> QUERY_TYPE { get; set; }
        public string QUERY_COLUMN_FORMAT { get; set; }
        public string QUERY_RELATION { get; set; }
        public string QUERY_RELATION_COLUMN_FORMAT { get; set; }
    }
}
