//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_SERVICE
    {
        public System.Guid ID { get; set; }
        public string SERVICE_HOST_NAME { get; set; }
        public string SERVICE_IP_ADDRESS { get; set; }
        public Nullable<short> SERVICE_PORT_ADDRESS { get; set; }
        public Nullable<System.DateTime> START_TIME { get; set; }
    }
}
