//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_STANDARD_REPORTS_PROP
    {
        public int ID { get; set; }
        public Nullable<int> Report_ID { get; set; }
        public string Column_Name { get; set; }
        public string Type { get; set; }
        public Nullable<int> Action_Type { get; set; }
        public string Parameters { get; set; }
        public Nullable<int> Show_Mode { get; set; }
        public Nullable<int> Divided_By_Thousand { get; set; }
    }
}
