//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_TABLE_SEQUENCES
    {
        public int ID { get; set; }
        public int BRANCH_ID { get; set; }
        public string TABLE_NAME { get; set; }
        public string SEQUENCE_NAME { get; set; }
        public int START_VALUE { get; set; }
        public int INCREMENT_VALUE { get; set; }
        public int MIN_VALUE { get; set; }
        public int MAX_VALUE { get; set; }
        public int CURRENT_VALUE { get; set; }
    }
}
