//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_USER
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public string NAME { get; set; }
        public string PWD { get; set; }
        public Nullable<int> RIGHTS { get; set; }
        public Nullable<int> USERGROUP { get; set; }
        public Nullable<short> LOCKED { get; set; }
        public Nullable<short> TRACELOG { get; set; }
        public Nullable<int> BRANCH { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public Nullable<System.DateTime> DESTROYDATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<int> LAST_UPDATED_BY { get; set; }
        public Nullable<int> DB_TYPE { get; set; }
    }
}
