//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAWDBDEBTSCHEDULE
    {
        public int ID { get; set; }
        public Nullable<int> CONTRACT { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DESTROYDATE { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public Nullable<short> MONTHSCOUNT { get; set; }
        public Nullable<int> PAYMENT { get; set; }
        public Nullable<decimal> RESCHEDULEDAMOUNT { get; set; }
        public Nullable<short> ISFORNEWDUTY { get; set; }
        public Nullable<System.DateTime> COMPLETEDATE { get; set; }
        public Nullable<int> COURTCASE { get; set; }
    }
}
