//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAWDBSUPPLYNODE
    {
        public int ID { get; set; }
        public Nullable<short> ALWAYSENABLED { get; set; }
        public Nullable<int> BRANCH { get; set; }
        public Nullable<short> CALCMETHOD { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DESTROYDATE { get; set; }
        public Nullable<double> GOODSDEFAULT { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public string NAME { get; set; }
        public Nullable<short> NOTSUPPLYDAYS { get; set; }
        public Nullable<int> PARENT { get; set; }
        public string STAMPNUMBER { get; set; }
        public Nullable<short> SUPPLYNODETYPE { get; set; }
        public Nullable<int> SUPPLYSCHEDULE1 { get; set; }
        public Nullable<int> SUPPLYSCHEDULE2 { get; set; }
        public Nullable<decimal> SUPPLYTIME { get; set; }
        public Nullable<double> TUBEDIAMETER { get; set; }
    }
}
