//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAWDBRESCONTRACTCALC
    {
        public int ID { get; set; }
        public Nullable<int> BRANCH { get; set; }
        public Nullable<int> CALCINTERVAL { get; set; }
        public Nullable<short> CALCULATED { get; set; }
        public Nullable<decimal> DRAINAGECLCAMOUNT { get; set; }
        public Nullable<double> DRAINAGECLCGOODS { get; set; }
        public Nullable<decimal> DRAINAGESTMAMOUNT { get; set; }
        public Nullable<double> DRAINAGESTMGOODS { get; set; }
        public Nullable<decimal> DUTYEND { get; set; }
        public Nullable<decimal> DUTYSTART { get; set; }
        public Nullable<decimal> FSMCLEAR { get; set; }
        public Nullable<decimal> FSMMOVE { get; set; }
        public Nullable<short> HASDISCOUNT { get; set; }
        public Nullable<short> HASDRAINAGE { get; set; }
        public Nullable<short> HASIRRIGATION { get; set; }
        public Nullable<short> HASWATER { get; set; }
        public Nullable<decimal> IRRIGATIONCLCAMOUNT { get; set; }
        public Nullable<double> IRRIGATIONCLCGOODS { get; set; }
        public Nullable<decimal> IRRIGATIONSTMAMOUNT { get; set; }
        public Nullable<double> IRRIGATIONSTMGOODS { get; set; }
        public Nullable<int> KEYOBJECT { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public Nullable<decimal> PYMDEFAULTREGULARCORRECT { get; set; }
        public Nullable<decimal> PYMDEFAULTREGULARCURRENT { get; set; }
        public Nullable<decimal> PYMTRANSFERREGULARCORRECT { get; set; }
        public Nullable<decimal> PYMTRANSFERREGULARCURRENT { get; set; }
        public Nullable<decimal> WATERCLCAMOUNT { get; set; }
        public Nullable<double> WATERCLCGOODS { get; set; }
        public Nullable<decimal> WATERSTMAMOUNT { get; set; }
        public Nullable<double> WATERSTMGOODS { get; set; }
        public Nullable<short> HASCOUNTER { get; set; }
        public Nullable<short> HASCMDEFAULT { get; set; }
        public Nullable<short> HASCMGARDENSQUARE { get; set; }
        public Nullable<short> HASCMRESCOUNT { get; set; }
        public Nullable<short> HASCMSQUARE { get; set; }
        public Nullable<short> HASCMTUBESPEEDTIME { get; set; }
        public Nullable<short> HASCMYARDTAP { get; set; }
        public Nullable<short> HASCONDOMINIUM { get; set; }
        public Nullable<int> RESCOUNT { get; set; }
        public Nullable<decimal> CUSTOMSERVICEAMOUNT { get; set; }
        public Nullable<decimal> PENALTY { get; set; }
        public Nullable<int> OLDDUTYCALC { get; set; }
        public Nullable<decimal> DEBET2005 { get; set; }
        public Nullable<decimal> DEBET2006 { get; set; }
        public Nullable<decimal> DEBET2007 { get; set; }
        public Nullable<decimal> DEBET2008 { get; set; }
        public Nullable<decimal> DEBET2009 { get; set; }
        public Nullable<int> DEBTSCHEDULE { get; set; }
        public Nullable<decimal> DEBTSCHEDULEPYM { get; set; }
        public Nullable<decimal> NEWCREDITCOVEREDBYAMOUNT { get; set; }
        public Nullable<decimal> NEWCREDITCOVEREDBYFSM { get; set; }
        public Nullable<decimal> NEWCREDITCOVEREDBYPYMCORRECT { get; set; }
        public Nullable<decimal> NEWCREDITINCREMENTBYAMOUNTSTM { get; set; }
        public Nullable<decimal> NEWCREDITINCREMENTBYFSM { get; set; }
        public Nullable<decimal> NEWCREDITINCREMENTBYPYM { get; set; }
        public Nullable<decimal> NEWDEBETCOVEREDBYAMOUNTSTM { get; set; }
        public Nullable<decimal> NEWDEBETCOVEREDBYFSM { get; set; }
        public Nullable<decimal> NEWDEBETCOVEREDBYPYM { get; set; }
        public Nullable<decimal> NEWDEBETINCREMENTBYAMOUNT { get; set; }
        public Nullable<decimal> NEWDEBETINCREMENTBYFSM { get; set; }
        public Nullable<decimal> NEWDEBETINCREMENTBYPYMCORRECT { get; set; }
        public Nullable<decimal> PYM2005 { get; set; }
        public Nullable<decimal> PYM2006 { get; set; }
        public Nullable<decimal> PYM2007 { get; set; }
        public Nullable<decimal> PYM2008 { get; set; }
        public Nullable<decimal> PYM2009 { get; set; }
        public Nullable<decimal> DEBET2010 { get; set; }
        public Nullable<decimal> PYM2010 { get; set; }
        public Nullable<decimal> DEBET2011 { get; set; }
        public Nullable<decimal> PYM2011 { get; set; }
        public Nullable<decimal> DEBET2012 { get; set; }
        public Nullable<decimal> PYM2012 { get; set; }
        public Nullable<decimal> DEBET2013 { get; set; }
        public Nullable<decimal> PYM2013 { get; set; }
        public Nullable<decimal> DEBET2014 { get; set; }
        public Nullable<decimal> PYM2014 { get; set; }
        public Nullable<decimal> DEBET2015 { get; set; }
        public Nullable<decimal> PYM2015 { get; set; }
        public Nullable<decimal> DEBTSCHEDULEREMAININGDEBT { get; set; }
        public Nullable<decimal> DEBTSCHEDULECURRENTPAYMENT { get; set; }
        public Nullable<decimal> DEBET2016 { get; set; }
        public Nullable<decimal> PYM2016 { get; set; }
        public Nullable<decimal> DEBET2017 { get; set; }
        public Nullable<decimal> PYM2017 { get; set; }
    }
}
