//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAWDBINDICATION
    {
        public int ID { get; set; }
        public Nullable<int> BILLINGCYCLEVISIT { get; set; }
        public Nullable<int> COUNTER { get; set; }
        public Nullable<System.DateTime> EVENTDATE { get; set; }
        public Nullable<double> INDICATION { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public string NUMBER { get; set; }
        public Nullable<short> REGULAR { get; set; }
        public Nullable<int> INDICATIONMAP { get; set; }
        public Nullable<int> INDICATIONMAPINDEX { get; set; }
        public Nullable<int> PREVID { get; set; }
        public Nullable<double> PREVINDICATION { get; set; }
        public Nullable<short> PREVREGULAR { get; set; }
        public Nullable<short> ISTURNEDOVER { get; set; }
        public Nullable<short> PREVISTURNEDOVER { get; set; }
    }
}
