//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAWDBSTATEMENTMONTH
    {
        public int ID { get; set; }
        public Nullable<int> STATEMENT { get; set; }
        public Nullable<System.DateTime> EVENTDATE { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public string MEMO { get; set; }
        public Nullable<decimal> JANUARY { get; set; }
        public Nullable<decimal> FEBRUARY { get; set; }
        public Nullable<decimal> MARCH { get; set; }
        public Nullable<decimal> APRIL { get; set; }
        public Nullable<decimal> MAY { get; set; }
        public Nullable<decimal> JUNE { get; set; }
        public Nullable<decimal> JULY { get; set; }
        public Nullable<decimal> AUGUST { get; set; }
        public Nullable<decimal> SEPTEMBER { get; set; }
        public Nullable<decimal> OCTOBER { get; set; }
        public Nullable<decimal> NOVEMBER { get; set; }
        public Nullable<decimal> DECEMBER { get; set; }
    }
}
