//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAWDBSUPPLYNODECALC
    {
        public int ID { get; set; }
        public Nullable<int> BRANCH { get; set; }
        public Nullable<double> BUDGETCLCGOODS { get; set; }
        public Nullable<int> BUDGETPOINTSCOUNT { get; set; }
        public Nullable<int> BUDGETPOINTSWITHCNTCOUNT { get; set; }
        public Nullable<double> BUDGETSTMGOODS { get; set; }
        public Nullable<int> CALCINTERVAL { get; set; }
        public Nullable<short> CALCULATED { get; set; }
        public Nullable<int> CHILDSUPPLYNODESCOUNT { get; set; }
        public Nullable<double> CHILDSUPPLYNODESGOODS { get; set; }
        public Nullable<int> CHILDSUPPLYNODESWITHCNTCOUNT { get; set; }
        public Nullable<double> FREEGOODS { get; set; }
        public Nullable<double> GOODS { get; set; }
        public Nullable<short> HASCMDEFAULT { get; set; }
        public Nullable<short> HASCMTUBESPEEDTIME { get; set; }
        public Nullable<short> HASCOUNTER { get; set; }
        public Nullable<int> KEYOBJECT { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public Nullable<double> LOSS { get; set; }
        public Nullable<double> LOSSWITHOUTSTM { get; set; }
        public Nullable<double> NONBUDGETCLCGOODS { get; set; }
        public Nullable<int> NONBUDGETPOINTSCOUNT { get; set; }
        public Nullable<int> NONBUDGETPOINTSWITHCNTCOUNT { get; set; }
        public Nullable<double> NONBUDGETSTMGOODS { get; set; }
        public Nullable<double> RESCLCGOODS { get; set; }
        public Nullable<int> RESPOINTSCOUNT { get; set; }
        public Nullable<int> RESPOINTSWITHCNTCOUNT { get; set; }
        public Nullable<double> RESSTMGOODS { get; set; }
        public Nullable<int> TOTALRESDAYS { get; set; }
    }
}
