//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAWDBRESIDENTCONTRACT
    {
        public int ID { get; set; }
        public string APPARTMENT { get; set; }
        public Nullable<int> CITY { get; set; }
        public string COMMUNE { get; set; }
        public string EMAIL { get; set; }
        public string ENTRANCE { get; set; }
        public string FLOOR { get; set; }
        public string HOUSE { get; set; }
        public string SECTION { get; set; }
        public string STREET { get; set; }
        public string TOC1 { get; set; }
        public string TOC2 { get; set; }
        public string ZIP { get; set; }
        public Nullable<int> BRANCH { get; set; }
        public string CARD { get; set; }
        public Nullable<int> CATEGORY { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<System.DateTime> DESTROYDATE { get; set; }
        public string FAMILY { get; set; }
        public string FATHERNAME { get; set; }
        public Nullable<double> GARDENSQUARE { get; set; }
        public Nullable<double> GOODSDEFAULT { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public string NAME { get; set; }
        public string PASSPORT { get; set; }
        public Nullable<int> RESCOUNT { get; set; }
        public Nullable<double> SQUARE { get; set; }
        public Nullable<int> TERRITORY { get; set; }
        public string WHOGAVE { get; set; }
        public Nullable<short> COUNTERINSTALLATIONSUBJECT { get; set; }
        public Nullable<short> HOUSEKIND { get; set; }
        public Nullable<System.DateTime> PREVCONTRACTDATE { get; set; }
        public Nullable<int> CONTRACTGROUP { get; set; }
        public string LASTMODIFIEDDOCNUMBER { get; set; }
        public Nullable<int> BILLINGCYCLE { get; set; }
        public Nullable<double> PENALTYPERCENT { get; set; }
        public Nullable<System.DateTime> COUNTERCONTRACTDATE { get; set; }
        public Nullable<int> VFLAG { get; set; }
        public Nullable<int> STATUS { get; set; }
        public string SOCIALCARDNUMBER { get; set; }
        public Nullable<short> COUNTERNODE { get; set; }
        public Nullable<short> HASDEBTCOVERSCHEDULECONTRACT { get; set; }
        public string TOC3 { get; set; }
        public Nullable<double> LONGITUDE { get; set; }
        public Nullable<double> LATITUDE { get; set; }
        public string CENTER_GEOM { get; set; }
    }
}
