//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAWDBFINANCIALSTATEMENT
    {
        public int ID { get; set; }
        public Nullable<int> CONTRACT { get; set; }
        public Nullable<System.DateTime> EVENTDATE { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public string MEMO { get; set; }
        public string NUMBER { get; set; }
        public Nullable<int> STMTYPE { get; set; }
        public Nullable<decimal> AMOUNT2005 { get; set; }
        public Nullable<decimal> AMOUNT2006 { get; set; }
        public Nullable<decimal> AMOUNT2007 { get; set; }
        public Nullable<decimal> AMOUNT2008 { get; set; }
        public Nullable<decimal> AMOUNT2009 { get; set; }
        public Nullable<decimal> AMOUNT2010 { get; set; }
        public Nullable<decimal> AMOUNT2011 { get; set; }
        public Nullable<decimal> AMOUNT2012 { get; set; }
        public Nullable<decimal> AMOUNT2013 { get; set; }
        public Nullable<decimal> AMOUNT2014 { get; set; }
        public Nullable<decimal> AMOUNT2015 { get; set; }
        public Nullable<short> FSTCLASS { get; set; }
        public Nullable<decimal> TOTALAMOUNT { get; set; }
        public Nullable<decimal> AMOUNT2016 { get; set; }
        public Nullable<decimal> AMOUNT2017 { get; set; }
    }
}
