//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJODBQRREPORT
    {
        public int ID { get; set; }
        public Nullable<short> ALIGNMENT { get; set; }
        public string CACHEPROPS { get; set; }
        public string CLASSES { get; set; }
        public Nullable<int> COLOR { get; set; }
        public string COLUMNS { get; set; }
        public string CRITERIA { get; set; }
        public Nullable<int> DATA { get; set; }
        public Nullable<short> FONT_CHARSET { get; set; }
        public Nullable<int> FONT_COLOR { get; set; }
        public Nullable<int> FONT_HEIGHT { get; set; }
        public string FONT_NAME { get; set; }
        public Nullable<short> FONT_PITCH { get; set; }
        public Nullable<int> FONT_STYLE { get; set; }
        public string FORMALNAME { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public Nullable<short> LINESNUMBERINGKIND { get; set; }
        public Nullable<int> LISTINDEX { get; set; }
        public string NAME { get; set; }
        public string ORDERBYPROPS { get; set; }
        public string PARAMSLIST { get; set; }
        public Nullable<short> PRINTOBJECTSIFEMPTY { get; set; }
        public string QUERYNAME { get; set; }
        public string SUBTITLE1 { get; set; }
        public string SUBTITLE2 { get; set; }
        public string TITLE { get; set; }
        public string TOTALLINECAPTION { get; set; }
    }
}
