//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJODBPROPPRIVELEGE
    {
        public int ID { get; set; }
        public Nullable<short> ALLOWEDIT { get; set; }
        public Nullable<short> ALLOWVIEW { get; set; }
        public string CLS { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public string PROP { get; set; }
        public Nullable<int> USERGROUP { get; set; }
    }
}
