//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJODBQRLOOPLINE
    {
        public int ID { get; set; }
        public Nullable<short> ALIGNMENT { get; set; }
        public string CAPTION { get; set; }
        public string CHILDSNUMBERINGCOUNTER { get; set; }
        public Nullable<short> CHILDSNUMBERINGKIND { get; set; }
        public Nullable<int> COLOR { get; set; }
        public Nullable<short> FONT_CHARSET { get; set; }
        public Nullable<int> FONT_COLOR { get; set; }
        public Nullable<int> FONT_HEIGHT { get; set; }
        public string FONT_NAME { get; set; }
        public Nullable<short> FONT_PITCH { get; set; }
        public Nullable<int> FONT_STYLE { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public Nullable<int> LINEINDEX { get; set; }
        public string LOOPPROPNAME { get; set; }
        public Nullable<int> PARENTLINE { get; set; }
        public Nullable<short> PRINTLIST { get; set; }
        public Nullable<int> REPORT { get; set; }
        public Nullable<short> SORTKIND { get; set; }
        public string SORTPROPNAME { get; set; }
    }
}
