//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJODBUSER
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public string NAME { get; set; }
        public string PWD { get; set; }
        public Nullable<int> RIGHTS { get; set; }
        public Nullable<int> USERGROUP { get; set; }
        public Nullable<short> LOCKED { get; set; }
        public Nullable<short> TRACELOG { get; set; }
        public Nullable<int> BRANCH_ID { get; set; }
        public string BRANCH_NAME { get; set; }
    }
}
