//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJODBQUERY
    {
        public int ID { get; set; }
        public string CACHEPROPS { get; set; }
        public string CLASSES { get; set; }
        public string CRITERIA { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public string NAME { get; set; }
        public string ORDERBYPROPS { get; set; }
        public string PARAMSLIST { get; set; }
    }
}
