//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArmWater.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TJODBLIBVALUE259
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> CREATEDATE { get; set; }
        public Nullable<int> DATA { get; set; }
        public Nullable<System.DateTime> DESTROYDATE { get; set; }
        public Nullable<System.DateTime> LASTMODIFIED { get; set; }
        public Nullable<int> PROPTYPE { get; set; }
        public string PROPVALUE { get; set; }
        public Nullable<int> OLD_ID { get; set; }
    }
}
