//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Person", Namespace="http://schemas.datacontract.org/2004/07/WCFSampleApp")]
    [System.SerializableAttribute()]
    public partial class Person : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IBetService")]
    public interface IBetService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetService/GetValue", ReplyAction="http://tempuri.org/IBetService/GetValueResponse")]
        string GetValue(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetService/GetValue", ReplyAction="http://tempuri.org/IBetService/GetValueResponse")]
        System.Threading.Tasks.Task<string> GetValueAsync(int i);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetService/CalculateSin", ReplyAction="http://tempuri.org/IBetService/CalculateSinResponse")]
        double[] CalculateSin(double[] x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetService/CalculateSin", ReplyAction="http://tempuri.org/IBetService/CalculateSinResponse")]
        System.Threading.Tasks.Task<double[]> CalculateSinAsync(double[] x);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetService/GetPerson", ReplyAction="http://tempuri.org/IBetService/GetPersonResponse")]
        WpfApplication1.ServiceReference1.Person[] GetPerson();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBetService/GetPerson", ReplyAction="http://tempuri.org/IBetService/GetPersonResponse")]
        System.Threading.Tasks.Task<WpfApplication1.ServiceReference1.Person[]> GetPersonAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBetServiceChannel : WpfApplication1.ServiceReference1.IBetService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BetServiceClient : System.ServiceModel.ClientBase<WpfApplication1.ServiceReference1.IBetService>, WpfApplication1.ServiceReference1.IBetService {
        
        public BetServiceClient() {
        }
        
        public BetServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BetServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetValue(int i) {
            return base.Channel.GetValue(i);
        }
        
        public System.Threading.Tasks.Task<string> GetValueAsync(int i) {
            return base.Channel.GetValueAsync(i);
        }
        
        public double[] CalculateSin(double[] x) {
            return base.Channel.CalculateSin(x);
        }
        
        public System.Threading.Tasks.Task<double[]> CalculateSinAsync(double[] x) {
            return base.Channel.CalculateSinAsync(x);
        }
        
        public WpfApplication1.ServiceReference1.Person[] GetPerson() {
            return base.Channel.GetPerson();
        }
        
        public System.Threading.Tasks.Task<WpfApplication1.ServiceReference1.Person[]> GetPersonAsync() {
            return base.Channel.GetPersonAsync();
        }
    }
}
